# Generated by Django 5.2.3 on 2025-07-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='loyalty_points',
            field=models.IntegerField(default=0),
        ),
    ]
