# Generated by Django 5.2.3 on 2025-07-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_referral_code_customuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='extra_job_posting_credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='job_highlight_credits',
            field=models.IntegerField(default=0),
        ),
    ]
