# Generated by Django 5.2.3 on 2025-07-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_extra_job_posting_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='preferred_locations',
            field=models.TextField(blank=True, help_text='Virgülle ayrılmış tercih edilen lokasyonlar', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_product_categories',
            field=models.TextField(blank=True, help_text='Virgülle ayrılmış tercih edilen ürün kategorileri', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_skills',
            field=models.TextField(blank=True, help_text='Virgülle ayrılmış tercih edilen yetenekler', null=True),
        ),
    ]
