# Generated by Django 5.2.3 on 2025-07-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=10)),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
            options={
                'ordering': ('-application_date',),
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('salary_expectation', models.CharField(blank=True, max_length=100, null=True)),
                ('employment_type', models.CharField(choices=[('full-time', 'Tam Zamanlı'), ('part-time', 'Yarı Zamanlı'), ('contract', 'Sözleşmeli'), ('freelance', 'Serbest Çalışma'), ('internship', 'Staj')], default='full-time', max_length=20)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('highlighted', models.BooleanField(default=False)),
                ('is_spam', models.BooleanField(default=False)),
            ],
        ),
    ]
