# Generated by Django 5.2.3 on 2025-07-04 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['content_type', 'object_id'], name='contact_rep_content_8ed067_idx'),
        ),
    ]
