# Generated by Django 5.2.3 on 2025-06-30 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('membership_type', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro')], default='FREE', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_months', models.IntegerField(default=1)),
                ('max_job_postings', models.IntegerField(default=1)),
                ('highlight_listings', models.BooleanField(default=False)),
                ('featured_listings', models.BooleanField(default=False)),
                ('cv_pool_access', models.BooleanField(default=False)),
                ('analytics_access', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('membership_plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memberships.membershipplan')),
            ],
        ),
    ]
