# Generated by Django 5.2.3 on 2025-07-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='custom_integrations',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='membershipplan',
            name='priority_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='membershipplan',
            name='membership_type',
            field=models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('PRO', 'Pro'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=30),
        ),
    ]
