# Generated by Django 5.2.3 on 2025-07-01 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_membershipplan_custom_integrations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipplan',
            name='product_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
