# Generated by Django 5.2.3 on 2025-06-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Beklemede'), ('PROCESSING', 'Hazırlanıyor'), ('SHIPPED', 'Kargoya Verildi'), ('DELIVERED', 'Teslim Edildi'), ('CANCELLED', 'İptal Edildi')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
