# Generated by Django 5.2.3 on 2025-07-04 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('notification_type', models.CharField(choices=[('MESSAGE', 'New Message'), ('ORDER_UPDATE', 'Order Update'), ('JOB_ALERT', 'Job Alert'), ('MEMBERSHIP', 'Membership Update'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
